---
deployment:
  tasks:
    - export DEPLOYPATH=/home/carsomg/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R lib $DEPLOYPATH
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp blog.html $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp detail.html $DEPLOYPATH
    - /bin/cp feature.html $DEPLOYPATH
    - /bin/cp quote.html $DEPLOYPATH
    - /bin/cp service.html $DEPLOYPATH
    - /bin/cp team.html $DEPLOYPATH
    - /bin/cp testimonial.html $DEPLOYPATH
